# Site settings
title: pure大菠萝的果园
email: huangkemin1985@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 我热爱技术，希望技术能给人们的生活带来一些不同。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://github.com/huangkemin" # the base hostname & protocol for your site
twitter_username: huangkemin
github_username:  huangkemin

# Build settings
markdown: kramdown
